config/routes.rb
Imago::Application.routes.draw do

  resources :users, except: [:index] do
    resources :images, except: [:new]
  end
  
  root 'welcome#index'
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"

end

app/models/image.rb
class Image
  include Mongoid::Document
  
  belongs_to :user
  field :name, type: String
  field :image_url, type: String
  field :attachment
  mount_uploader :attachment, AttachmentUploader
  validates :name, presence: true

# left for later
  # def file_name
  #   self.attachment.path.split("/").last
  # end
 
end

app/models/user.rb
class User
  include Mongoid::Document
  # ActiveModel - SecurePassword has to be included separately
  # because of skipped ActiveRecord. AcitveRecord created a connection
  # for 'bcrypt' gem to ActiveModel has_secure_password method
  include ActiveModel::SecurePassword
  has_many :images, { :dependent => :destroy }

  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  validates :email, presence: true
  validates :name, presence: true
# don't forget to go to mongoid.yml file and uncomment
# raise_not_found_error: false to avoid errors on landing page, when user_id
# not found by session controller or any other controller
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  helper_method :current_user, :logged_in?
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  self.before_action(:load_user)
  self.before_action(:load_image, {only: [:show, :update, :destroy]})
  before_action :authenticate, :authorize
  
  def index
    @image = Image.new
    @images = @user.images.all.to_a
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @images}
    end
  end

  def show
    
  end

  def create
    @image = @user.images.create(image_params)
    redirect_to user_images_path
  end

  def update
    @image.update(image_params)
    render json: @image
  end

  def destroy
    @image.destroy
    redirect_to user_images_path
  end

  private

  def load_user
    return @user = current_user #User.find(params[:user_id])
  end

  def load_image
    return @image = Image.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:name, :image_url, :attachment, :user_id)
  end

  def authenticate
    unless logged_in?
      redirect_to root_path
    end
  end


  def authorize
    unless current_user == @user
      redirect_to root_path
    end
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
    render(:new)
  end

  def create
    #find if any user has that email
    user = User.find_by(email: params[:email])
    #if that user exists and it has password that was sent
    if user && (user.authenticate(params[:password]))
      #save the user_id in the session hash
      session[:user_id] = user.id
      # and redirect to that user's home page
      redirect_to user_path(user)
    else
      #the email/password is wrong!
      flash[:message] = "This email and password combination does not exist."
      # render "session/form"
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :authorize, only: [:show, :edit, :update]

  def new
    @user = User.new
    render(:new)
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render(:new)
    end
  end

  def show
  
  end

  def update
    @update_worked = @user.update(user_params)

    if @update_worked
      redirect_to user_path(@user)
    else
      render(:edit)
    end
  end

  def destroy
    @user.destroy
    session.destroy
    redirect_to root_path
  end

  private

  def load_user
    return @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def authenticate
    unless logged_in?
      redirect_to root_path
    end
  end

  def authorize
    unless current_user == @user
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.erb
<p class="panel callout">Add another image to you album</p>
<%= form_for  [@user, @image], url: user_images_path do |v| %>
   <%= v.label :name %>
  <%= v.text_field :name %>

  <%= v.label :image_url %>
  <%= v.text_field :image_url %>

  <%= v.hidden_field :attachment_cache %>
  <%= v.file_field :attachment %>
 
  <%= v.submit class:"small button" %>
<% end %>

app/views/images/_menu.html.erb
<li class="has-dropdown">
  <a href="#">Image menu</a>
  <ul class="dropdown">
    <li><%= link_to "Delete this picture", user_image_path(@user, @image), method: "delete", data: { confirm: "Are you sure you want to delete this picture?"} %></li>
    <li id="edit-button"><a href="#">Edit this picture</a></li>
  </ul>
</li>

app/views/images/index.html.erb
<section class="row">
  <div class="small-6 columns">
    <div id="image_form">
      <%= render "form" %>
    </div>
  </div>
  <div class="small-6 columns">
    <div id="album_notes" class="panel callout">
      <p>Please note that, whenever you add image from external url or your computer, you can edit it, but you won't be able to save due to security restrictions. If you'd like to overcome it, please save the desired image to your computer and then upload it to this application.</p>
      <p>If you're going to edit existing image, please remember it's name and enter it later to overwrite it.</p>
    </div>
  </div>
</section>
<section class="row">
  <div class="small-12 columns" id="album_table">
    <ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-4">
        <% @images.each do |img| %>
        <% unless img.image_url.empty? %>
            <li><p><%= img.name %></p><%= link_to image_tag(img.image_url), user_image_path(@user, img), class: "th album-image-back" %></li>
        <% else %>
          <li><p><%= img.name %></p><%= link_to image_tag(img.attachment), user_image_path(@user, img), class: "th album-image-back" %></li>
          <% end %>
        <% end %>
    </ul>
  </div>
</section>

app/views/images/show.html.erb
<section class="row">
  <div class="small-12 large-12 columns">
    <% unless @image.image_url.empty? %>
      <%= image_tag @image.image_url, :id => "pic", class: "album-image-back filter-blur" %>
    <% else %>
    <%= image_tag @image.attachment, :id => "pic", class: "album-image-back" %>
    <% end %>
  </div>
</section>

<script type="text/javascript">
  editImageGrab("<%= @user.id %>");
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "IMAGO: Image editor" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <script type="text/javascript">localStorage["image"];</script>
  <body>
    <header>
      <nav class="top-bar" data-topbar>
        <section class="top-bar-section">
        <ul class="left">
          <li><%= link_to "Home", root_path %></li>
          <% if logged_in? %>
          <li><%= link_to "My album", user_images_path(current_user) %></li>
          <li><%= link_to "Canvas", user_path(current_user), class:"button" %></li>
          <% if params[:action] == "show" && params[:controller] == "users" %>
          <li class="has-dropdown">
            <a href="#">Edit</a>
            <ul class="dropdown">
              <li id="copy"><a>Copy Current Image</a></li>
              <li id="paste"><a>Paste Copied Image</a></li>
            </ul>
          </li>
          <li class="has-dropdown">
            <a href="#">Filter</a>
            <ul class="dropdown">
              <li id="invert-colors"><a>Invert Colors</a></li>
              <li id="greyscale"><a>Greyscale Image</a></li>
              <li id="pixel"><a>Pixelate Image</a></li>
            </ul>
          </li>
          <li class="has-dropdown">
            <a href="#">Brightness</a>
            <ul class="dropdown">
              <li id="brightness"><a>Brighter</a></li>
              <li id="darkness"><a>Darker</a></li>
            </ul>
          </li>
          <% end %>
        </ul>
        
        <ul class="right">
          <% if params[:action] == 'show' && params[:controller] == 'images' %>
          <%= render "menu" %>
          <% end %>
          <li class="has-dropdown">
            <a href="#">User menu</a>
            <ul class="dropdown">
              <li><%= link_to "Update your profile", edit_user_path(current_user) %></li>
              <li>
                <%= link_to "Delete my profile", user_path(current_user), method: "delete", data: { confirm: "Are you sure you want to delete your profile? You'll loose your album and all your saved pictures"} %>
              </li>
            </ul>
          </li>
          <li><%= link_to("Log Out #{current_user.name}!", "/session", method: "delete") %></li>
          <% else %>
          <li><%= link_to "Sign up", new_user_path %></li>
          <li class="has-form">
            <div class="row collapse">
            <%= render "session/form" %>
            </div>
          </li> 
        <% end %>
        </ul>
        </section>
      </nav>
      
    </header>
    <%= javascript_tag("$(function(){ $(document).foundation(); });") %>
    <%= yield %>
    <% if !logged_in? %>
      <%= javascript_tag("loginPlaceholders();") %>
    <% end %>
  </body>
</html>

app/views/session/_form.html.erb
<%= form_tag "/session" do %>

  <div class="small-4 columns">
  <%= email_field_tag :email %>
  </div>
  <div class="small-4 columns">
  <%= password_field_tag :password %>
  </div>
  <div class="small-3 columns">
  <%= submit_tag "Log in!", class:"alert button" %>
  </div>
  
<% end %>

<% unless flash[:message].nil? %>
  <div id="errors">
    <h3>Errors!</h3>
    <ul>
      <li><em><%= flash[:message] %></em></li>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br/>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br/>

  <%= f.label :email %>
  <%= f.email_field :email %>
  <br/>

  <%= f.submit @user.name.nil? ? "Join!" : "Save Changes", class:"small button" %>
<% end %>

app/views/users/edit.html.erb
<h2>Update user <%= @user.name %></h2>
<section class="row">
  <div class="small-12 columns">
    <% unless @update_worked %>
    <div id="errors">
      <ul>
        <% @user.errors.messages.each do |field,error| %>
          <li><em><%= "#{field.capitalize} #{error.first}!" %></em></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= render "form" %>

  </div>
</section>

app/views/users/new.html.erb
<h2>Create a new user here!</h2>
<section class="row">
  <div class="small-6 columns">
    <% unless @user.name.nil? %>
    <div id="errors">
      <h3>Errors!</h3>
      <ul>
        <% @user.errors.messages.each do |field,error| %>
          <li><em><%= "#{field.capitalize} #{error.first}!" %></em></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <%= render "form" %>
  </div>
  <div class="small-6 columns">
    <div id="user_new_notes" class="panel callout">
      <p>Please don't forget your password. If you ever forget it, send me an <%= mail_to "xfiler@ymail.com", "Email" %> I will be able to send to you temporary password to access your account</p>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="row">

  <div id="first">
    <div class="small-6 large-6 columns">
      <ul class="button-group">
        <!-- <li><button class="tiny success button" id="brightness">Brighten Image</button></li>
        <li><button class="tiny success button" id="darkness">Darken Image</button></li> -->
        <!-- <li><button class="tiny alert button" id="copy">Copy Current Image</button></li> -->
        <!-- <li><button class="tiny secondary button" id="invert-colors">Invert Colors</button></li> -->
      </ul>
      <ul class="button-group">
        <!-- <li><button class="tiny alert button" id="paste">Resotre From Buffer</button></li> -->
        <!-- <li><button class="tiny secondary button" id="greyscale">Greyscale Image</button></li> -->
      </ul>
      <ul class="button-group">
        <!-- <li><button class="tiny button" id="pixel">Pixelate Image</button></li> -->
      </ul>
    </div>
    <div class="small-6 large-6 columns panel callout">
      <p>Please click "Copy Current Image" button before you start editing your image. Once you make a mistake or want to revert to the original, you'll be able to click "Paste copied image" to get back.</p>
    </div>
  </div>

</section>

<section class="row" id="canvas-row">

  <div id="second">  
    <div id="toolbar">
      <div class="range-slider round" data-slider="10" data-options="display_selector: #sliderOutput1;">
        <span class="range-slider-handle"></span>
        <span class="range-slider-active-segment"></span>
        <input id="sliderOutput2" type="hidden">
      </div>
      <div id="rad">
        Radius <span id="sliderOutput1"></span>
      </div>
      <div id="resolution">
      </div>
      <input type='text' class="basic"/>
      <em id='basic-log'></em>
    </div>

    <canvas id="canvas" style="border: 1px solid black">
      Sorry, your browser doesn't support the cavas.
    </canvas>
  </div>

</section>
<script type="text/javascript">
  $(".basic").spectrum({
      color: "#f00"
  });
  canvasFunc();
  colorPickerFunc();
  radiusFunc();
  saveImageFunc("<%= @user.id %>");
  insertImageInCanvasFunc();
</script>

app/views/welcome/index.html.erb
<secton class="row">
  <div id="index" class="small-7 small-centered columns">
    <div class="panel callout">
  <h1>Welcome to Imago<h1>
    <h3>Imago - simple web based image editor</h3>
    <p>"Imago" is a latin word and it means image in English</p>
    <p>Although my application derives its name from latin word. There are couple more meanings of this word, that could be of your interest:<br>
      1.an insect in its final, adult, sexually mature, and typically winged state.</p>
      <p>2.an idealized mental image of another person or the self.</p>
    </div>
  </div>
</section>

<section class="row">
  <div id="about-app" class="small-7 small-centered columns">
    <div class="panel callout">
    <p>The major features of this application are:</p>
    <ul>
      <li>User can create his account with minimum personal information.</li>
      <li>User can draw a sketch choosing different thikness of brush and choosing one of several colors available in the current version</li>
      <li>
        User can upload an image via link from internet or from his computer.</li>
        <li>User can view his image album, look at any image closer and edit it in the editor, then save it and overwrite it</li>
      </ul>
      <br />
      <h4>Languages and technologies I've used</h4>
      <ul>
        <li>Back-end: Ruby on Rails 4.0</li>
        <li>Non relational database MongoDB and Mongoid ORM to control it. Uploaded images are stored on Amazon S3 Web Services</li>
        <li>The logic of the actual editor is written in JavaScript with elemnts of jQuery and AJAX thecnics</li>
      </ul>
      <br/>
      <p>Please note, that the canvas application may not function properly in browsers besides Chrome. If you experience difficulty using brush on canvas or don't even see the field to draw, please install Chrome</p>
    </div>
  <div>
</section>

<section class="row">
  <div id="about-author" class="small-7 small-centered columns">
    <div class="panel callout">
      <h4>Hello, my name is Dmitry Jum</h4>
      <p>I am junior full stack web developer. My major interstes in developments are programming in langugaes like Ruby, JavaScript and frameworks related to them. I am not very strong in web design, however I will be working progressivly on design of this editor<p>
        <p> If you have questions, suggestions, reccomendations, feel free to get in touch with me over <%= mail_to "dmitryjum@gmail.com", "Email" %>, find me on <%= link_to "LinkedIn", "http://www.linkedin.com/in/dmitryjum/" %> or check my personal page at <%= link_to "www.dmitryjum.com", "http://www.dmitryjum.com" %></p>
      </div>
    </div>
  </section>